### ISSUE TITLE
[Pregunta] Algunas features y preguntas

### ISSUE THREAD

**Issue by cristiangauma** [themonti/MegaDown#1]
Llevo mucho tiempo esperando que alguien hiciese un downloader en CLI para mega.co.nz, hasta tal punto que si para después de marzo no había ninguno, iba a empezar a mirarme yo mas a fondo toda la API de mega.

La cosa es que funciona muy muy bien, y me gustaría dejar aquí algunas features que de seguro harían un "level up" a la aplicación:
- Resumen de las descargas (si es posible)
- Escoger el directorio donde iran las descargas
- Manager de links: por ejemplo, que coja los links de un .txt y sepa en todo momento cuales se ha descargado y cuales no (escupiendo los últimos links en un archivo de /tmp por ejemplo)
- Limite de velocidad de descarga
- Modo Daemon: tener un daemon en permanente escucha y con algún comando añadir la descarga al daemon.

Voy a empezar a mirarme Python, ya que con bash algunas de las features que te digo las sabría hacer sin problemas... pero con Python no. A ver si puedo ayudar en el desarrollo :).

**Comment by themonti** [comment]
Muchas gracias por tus aportaciones Cristian,

las tenía ya recogidas en mi hoja de ruta personal ademas de otras como el ajuste de conexiones abiertas, una mini interfaz web, etc...pero me parecen muy buenas aportaciones por lo que las incluiré en la lista.

Espero no tardar mucho en llevarlas acabo, de todos modos si te pones las pilas con Python, te agradeceré las aportaciones, jejeje.

Lo dicho, gracias.
